# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:latest
      options: --network-alias testHost
    env:
      SELENIUM_HUB_HOST: hub
    services:
      hub:
        image: selenium/hub:3.141.59-gold
      firefox:
        image: selenium/node-firefox:3.141.59-gold
        env:
          HUB_HOST: hub
          HUB_PORT: 4444
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: main
        path: main
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
    - name: Install allure
      run: |
        curl -o allure-2.13.9.tgz -Ls https://github.com/allure-framework/allure2/releases/download/2.13.9/allure-2.13.9.tgz
        tar -zxvf allure-2.13.9.tgz -C /opt/
        ln -s /opt/allure-2.13.9/bin/allure /usr/bin/allure
    - name: Install Java
      run: |
        apt-get update
        apt-get install -y default-jre
    - name: Install allure-pytest
      run: pip install allure-pytest
    - name: Create a temp artifact folder named `output`
      run: mkdir output
    - name: Run Tests
      run: pytest --alluredir=output
    - name: Collect Allure files and generate allure-report folder
      run: allure generate output
    - name: Publishing Allure artifact to GitHub Actions
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: allure-report
    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      #id: allure-report
      with:
        allure_results: allure-results
        #gh_pages: gh-pages
        #allure_report: allure-report
        allure_history: allure-history
        keep_reports: 20
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history