# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
#     container:
#       image: python:latest
#       options: --network-alias testHost
#     env:
#       SELENIUM_HUB_HOST: hub
#     services:
#       hub:
#         image: selenium/hub:3.141.59-gold
#       firefox:
#         image: selenium/node-firefox:3.141.59-gold
#         env:
#           HUB_HOST: localhost
#           HUB_PORT: 4444
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Chrome and Firefox
      run: |
        sudo apt install google-chrome-stable
        sudo apt-get install firefox
    - name: Install seleniumbase
      run: pip install seleniumbase
    - name: Install chromedriver and geckodriver (Firefox Webdriver)
      run: |
        seleniumbase install chromedriver
        seleniumbase install geckodriver
    - name: Install allure
      run: pip install allure-pytest
    - name: Create a temp artifact folder named `output`
      run: mkdir output
    - name: Run Tests
      run: pytest --alluredir=output
    - name: Collect Allure files and generate allure-report folder
      run: allure generate output
    - name: Publishing Allure artifact to GitHub Actions
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: allure-report
